### ISSUE TITLE
Footnote does not appear

### ISSUE THREAD

**Issue by Petitprout** [pcafrica/focus-beamertheme#31]
Hello, 

I use focus and i want to put a footnote on a frame, on the focus demo you juste use`\footnote{\url{https://fonts.google.com/specimen/Fira+Sans}}` for instance but when i use it on my beamer, with focus template, it just shows the 1 but not the footnote.

**Comment by pcafrica** [comment]
Are you using the latest release? Can you provide a minimal working example?
